<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'error/404'               => __DIR__ . '/view/error/404.phtml',
    'error/index'             => __DIR__ . '/view/error/index.phtml',
    'application/index/index' => __DIR__ . '/view/application/index/index.phtml',
);
